version: '3'

services:
    horus-debian:
        init: true
        build:
            context: .
            dockerfile: .devcontainer-debian/Dockerfile.debian
        volumes:
            - .:/workspaces/horus:cached
            - /var/run/docker.sock:/var/run/docker-host.sock
            - ~/.ssh:/home/vscode/.ssh:cached
            - ~/.docker:/home/vscode/.docker:cached
            - horus-bashhistory-debian:/commandhistory
        user: vscode
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined    
        # command: /bin/sh -c "while sleep 1000; do :; done"    

    horus-fedora:
        init: true
        build:
            context: .
            dockerfile: .devcontainer-fedora/Dockerfile.fedora
        volumes:
            - .:/workspaces/horus:cached
            - /var/run/docker.sock:/var/run/docker-host.sock
            - ~/.ssh:/home/vscode/.ssh:cached
            - ~/.docker:/home/vscode/.docker:cached
            - horus-bashhistory-fedora:/commandhistory
        user: vscode
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined    
        # command: /bin/sh -c "while sleep 1000; do :; done"    

volumes:
    horus-bashhistory-debian:
    horus-bashhistory-fedora:
