version: '3'

services:
    horus:
        init: true
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ..:/workspaces/horus:cached
            - /var/run/docker.sock:/var/run/docker-host.sock
            - ~/.ssh:/home/vscode/.ssh:cached
            - ~/.docker:/home/vscode/.docker:cached
            - ~/.balena:/home/vscode/.balena:cached
            - horus-bashhistory:/commandhistory
        user: vscode
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined    
        # command: /bin/sh -c "while sleep 1000; do :; done"    

volumes:
    horus-bashhistory:
